// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_sandman_delta");
	self attach( "head_hero_sandman_delta", "", 1 );

	//self.hatModel = "hat_opforce_merc_b";
	//self attach(self.hatModel);

	// if ( issubstr( self.headModel, "hat" ) )
	// {
	// 	self.hatModel = "hat_opforce_merc_b";
	// 	self attach(self.hatModel);
	// }
	self.voice = "russian";
}

precache()
{
	precacheModel("body_hero_sandman_delta");
	precacheModel("head_hero_sandman_delta");
}
