// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_tank_crew_b");
	self attach( "head_tank_b_pilot", "", 1 );

	//self.hatModel = "hat_opforce_merc_b";
	//self attach(self.hatModel);

	// if ( issubstr( self.headModel, "hat" ) )
	// {
	// 	self.hatModel = "hat_opforce_merc_b";
	// 	self attach(self.hatModel);
	// }
	self.voice = "russian";
}

precache()
{
	precacheModel("body_tank_crew_b");
	precacheModel("head_tank_b_pilot");
}
