// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_elite_assault_ab");
	self attach( "head_delta_elite_a", "", 1 );

	//self.hatModel = "hat_opforce_merc_b";
	//self attach(self.hatModel);

	// if ( issubstr( self.headModel, "hat" ) )
	// {
	// 	self.hatModel = "hat_opforce_merc_b";
	// 	self attach(self.hatModel);
	// }
	self.voice = "russian";
}

precache()
{
	precacheModel("body_delta_elite_assault_ab");
	precacheModel("head_delta_elite_a");
}
