// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_elite_shotgun_a");
	self attach( "head_delta_elite_c", "", 1 );

	//self.hatModel = "hat_opforce_merc_b";
	//self attach(self.hatModel);

	// if ( issubstr( self.headModel, "hat" ) )
	// {
	// 	self.hatModel = "hat_opforce_merc_b";
	// 	self attach(self.hatModel);
	// }
	self.voice = "russian";
}

precache()
{
	precacheModel("body_delta_elite_shotgun_a");
	precacheModel("head_delta_elite_c");
}
